// Expanded bootstrap seed of large, CSR-mandatory Indian companies (drawn from
// the BSE500 / Nifty large- & mid-cap universe — every one crosses the Companies
// Act Section 135 net-worth/turnover/profit thresholds, so all are CSR-obligated).
//
// Used to bootstrap the database past 100+ entities without depending on web
// search (search-free mode, see config.ts). Names are deduped against existing
// rows before insertion. Categories are coarse; enrichment refines the rest.

export interface SeedCompany { name: string; category: 'company' | 'bank' | 'psu'; }

export const EXPANDED_COMPANIES: SeedCompany[] = [
  // IT / Tech
  { name: 'Infosys', category: 'company' },
  { name: 'HCL Technologies', category: 'company' },
  { name: 'Tech Mahindra', category: 'company' },
  { name: 'LTIMindtree', category: 'company' },
  { name: 'Persistent Systems', category: 'company' },
  { name: 'Coforge', category: 'company' },
  { name: 'Mphasis', category: 'company' },
  { name: 'Oracle Financial Services Software', category: 'company' },
  // Banks / NBFC / Finance
  { name: 'ICICI Bank', category: 'bank' },
  { name: 'Axis Bank', category: 'bank' },
  { name: 'IndusInd Bank', category: 'bank' },
  { name: 'Yes Bank', category: 'bank' },
  { name: 'IDFC First Bank', category: 'bank' },
  { name: 'Federal Bank', category: 'bank' },
  { name: 'Canara Bank', category: 'bank' },
  { name: 'Union Bank of India', category: 'bank' },
  { name: 'Bajaj Finance', category: 'company' },
  { name: 'Bajaj Finserv', category: 'company' },
  { name: 'HDFC Life Insurance', category: 'company' },
  { name: 'SBI Life Insurance', category: 'company' },
  { name: 'ICICI Prudential Life Insurance', category: 'company' },
  { name: 'ICICI Lombard General Insurance', category: 'company' },
  { name: 'Cholamandalam Investment and Finance', category: 'company' },
  { name: 'Shriram Finance', category: 'company' },
  { name: 'Muthoot Finance', category: 'company' },
  { name: 'Power Finance Corporation', category: 'psu' },
  { name: 'REC Limited', category: 'psu' },
  { name: 'LIC of India', category: 'psu' },
  // FMCG / Consumer
  { name: 'Nestle India', category: 'company' },
  { name: 'Britannia Industries', category: 'company' },
  { name: 'Dabur India', category: 'company' },
  { name: 'Marico', category: 'company' },
  { name: 'Godrej Consumer Products', category: 'company' },
  { name: 'Colgate-Palmolive India', category: 'company' },
  { name: 'Tata Consumer Products', category: 'company' },
  { name: 'United Spirits', category: 'company' },
  { name: 'Varun Beverages', category: 'company' },
  { name: 'Procter & Gamble Hygiene', category: 'company' },
  { name: 'Emami', category: 'company' },
  // Auto
  { name: 'Maruti Suzuki India', category: 'company' },
  { name: 'Tata Motors', category: 'company' },
  { name: 'Hero MotoCorp', category: 'company' },
  { name: 'Eicher Motors', category: 'company' },
  { name: 'TVS Motor Company', category: 'company' },
  { name: 'Ashok Leyland', category: 'company' },
  { name: 'Bosch India', category: 'company' },
  { name: 'Motherson Sumi Wiring', category: 'company' },
  { name: 'Balkrishna Industries', category: 'company' },
  { name: 'MRF', category: 'company' },
  // Pharma / Healthcare
  { name: 'Sun Pharmaceutical Industries', category: 'company' },
  { name: "Dr Reddy's Laboratories", category: 'company' },
  { name: 'Divi’s Laboratories', category: 'company' },
  { name: 'Lupin', category: 'company' },
  { name: 'Aurobindo Pharma', category: 'company' },
  { name: 'Torrent Pharmaceuticals', category: 'company' },
  { name: 'Biocon', category: 'company' },
  { name: 'Zydus Lifesciences', category: 'company' },
  { name: 'Alkem Laboratories', category: 'company' },
  { name: 'Apollo Hospitals Enterprise', category: 'company' },
  { name: 'Max Healthcare Institute', category: 'company' },
  { name: 'Fortis Healthcare', category: 'company' },
  // Energy / Oil & Gas / Power
  { name: 'Reliance Industries', category: 'company' },
  { name: 'Adani Enterprises', category: 'company' },
  { name: 'Adani Green Energy', category: 'company' },
  { name: 'Adani Ports and SEZ', category: 'company' },
  { name: 'Adani Power', category: 'company' },
  { name: 'Tata Power', category: 'company' },
  { name: 'Power Grid Corporation of India', category: 'psu' },
  { name: 'GAIL India', category: 'psu' },
  { name: 'Bharat Petroleum Corporation', category: 'psu' },
  { name: 'Hindustan Petroleum Corporation', category: 'psu' },
  { name: 'Coal India', category: 'psu' },
  { name: 'NHPC', category: 'psu' },
  { name: 'JSW Energy', category: 'company' },
  { name: 'Torrent Power', category: 'company' },
  // Metals / Mining / Cement
  { name: 'Tata Steel', category: 'company' },
  { name: 'JSW Steel', category: 'company' },
  { name: 'Hindalco Industries', category: 'company' },
  { name: 'Vedanta', category: 'company' },
  { name: 'Steel Authority of India', category: 'psu' },
  { name: 'NMDC', category: 'psu' },
  { name: 'Jindal Steel & Power', category: 'company' },
  { name: 'UltraTech Cement', category: 'company' },
  { name: 'Ambuja Cements', category: 'company' },
  { name: 'ACC', category: 'company' },
  { name: 'Shree Cement', category: 'company' },
  { name: 'Dalmia Bharat', category: 'company' },
  // Infra / Engineering / Capital goods
  { name: 'Siemens India', category: 'company' },
  { name: 'ABB India', category: 'company' },
  { name: 'Havells India', category: 'company' },
  { name: 'Cummins India', category: 'company' },
  { name: 'BEL - Bharat Electronics', category: 'psu' },
  { name: 'Hindustan Aeronautics', category: 'psu' },
  { name: 'Container Corporation of India', category: 'psu' },
  { name: 'GMR Airports Infrastructure', category: 'company' },
  // Telecom / Media
  { name: 'Bharti Airtel', category: 'company' },
  { name: 'Vodafone Idea', category: 'company' },
  { name: 'Indus Towers', category: 'company' },
  { name: 'Zee Entertainment Enterprises', category: 'company' },
  { name: 'PVR INOX', category: 'company' },
  // Chemicals / Paints / Fertiliser
  { name: 'Pidilite Industries', category: 'company' },
  { name: 'Berger Paints India', category: 'company' },
  { name: 'SRF', category: 'company' },
  { name: 'UPL', category: 'company' },
  { name: 'Tata Chemicals', category: 'company' },
  { name: 'Coromandel International', category: 'company' },
  { name: 'Deepak Nitrite', category: 'company' },
  { name: 'Aarti Industries', category: 'company' },
  // Consumer durables / Retail / Misc
  { name: 'Titan Company', category: 'company' },
  { name: 'Avenue Supermarts (DMart)', category: 'company' },
  { name: 'Trent', category: 'company' },
  { name: 'Voltas', category: 'company' },
  { name: 'Whirlpool of India', category: 'company' },
  { name: 'Page Industries', category: 'company' },
  { name: 'Bata India', category: 'company' },
  { name: 'Astral', category: 'company' },
  { name: 'Supreme Industries', category: 'company' },
  { name: 'InterGlobe Aviation (IndiGo)', category: 'company' },
  { name: 'DLF', category: 'company' },
  { name: 'Godrej Properties', category: 'company' },
  { name: 'Oberoi Realty', category: 'company' },
  { name: 'Indian Hotels Company', category: 'company' },
  { name: 'Info Edge India', category: 'company' },
];
